version: "3"
services:
  db:
    image: postgres:9.6.17
    environment:
      POSTGRES_DB: target_test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
