name: Smoke Test

on:
  repository_dispatch:
    types: [smoke_test]  # Custom event type
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    description: 'Run smoke tests manually'
  push:
    branches:
      - master

jobs:
  smoke-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4


      - name: Start PG test container
        run: docker compose up -d --build db


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'


      - name: Setup current repository dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install ".[tests]"


      - name: Run tests
        env: LOGGING_CONF_FILE: target_postgres/logging.conf
        run: |
          source .venv/bin/activate
          OUTPUT_FILE="smoke_test_output.log"
          echo "OUTPUT_FILE=$OUTPUT_FILE" >> $GITHUB_ENV

          # Initialize test status flag
          TEST_FAILED=0

          # Run the test and capture both stdout and stderr
          pytest tests > "$OUTPUT_FILE" 2>&1 || TEST_FAILED=1
          echo "TEST_FAILED=$TEST_FAILED" >> $GITHUB_ENV


      - name: Shutdown PG test container
        run: docker compose down


      - name: Output test results
        run: |
          cat "${{ env.OUTPUT_FILE }}"

          # Exit based on test status
          if [ ${{ env.TEST_FAILED }} -eq 1 ]; then
            exit 1
          else
            exit 0
          fi